### ISSUE TITLE
Requirements isn't finished yet!

### ISSUE THREAD

**Issue by Danct12** [aurieh/node-volt#3]
"chalk": "^1.1.3",
    "cheerio": "^0.20.0",
    "discordie": "^0.7.6",
    "eris": "^0.2.5",
    "needle": "^1.0.0",
    "refresher": "0.0.8",
    "youtube-dl": "^1.11.1"

**Comment by aurieh** [comment]
`refresher` is not required, and eris isnt really eris, its `abalabahaha/eris`. Will update later

**Comment by aurieh** [comment]
Forgot to leave the message: #b037365 fixed this
